(OK) Unloading intelmpi 2018.4.274
(!!) no SLURM environment present, environment broken?
(OK) Unloading Intel Suite 19.0.1.144
(OK) Loading gcc system-default
(OK) Intel MPI Suite 2018.4.274 loaded.
(!!) no SLURM environment present, environment broken?
(OK) Loading python 3.8.7
(!!) The SciPy Stack is available: http://www.scipy.org/stackspec.html
 Built with GCC compilers.
(OK) Loading cuda 11.1.1
(!!) We are changing the naming scheme for the CUDA module. cuda/112 will become cuda/11.2 etc. The old version names will soon be deprecated, please update your scripts to avoid problems in the future.
(OK) Loading cudnn 8.0.5
Traceback (most recent call last):
  File "run_config.py", line 21, in <module>
    main()
  File "run_config.py", line 17, in main
    start_fl(config)
  File "/rwthfs/rz/cluster/home/uu852150/repos/CosDefence/federated_learning/FL_basic.py", line 817, in start_fl
    client_data_loaders = create_client_data_loaders(total_clients, data_folder, config['BATCH_SIZE'])
  File "/rwthfs/rz/cluster/home/uu852150/repos/CosDefence/federated_learning/prepare_data.py", line 188, in create_client_data_loaders
    img_tensors = torch.load(img_tensor_file)  # this contains 494 images, currently 76
  File "/home/uu852150/.local/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/uu852150/.local/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/uu852150/.local/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/rwthfs/rz/cluster/home/uu852150/repos/CosDefence/data/mnist/fed_data/label_flip0/poisoned_40CLs/client_0_img.pt'
